(function(root){
  "use strict";
  const C=root.DietCore,API="/MMM-DietCalories/api",LABELS={kcal:"Calories",protein:"Protein",carbs:"Carbohydrates",fat:"Fat",water:"Water"};
  const fmt=(value,decimals=0)=>new Intl.NumberFormat("en-GB",{maximumFractionDigits:decimals}).format(value);
  const dateLabel=key=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(key+"T12:00:00Z"));
  const shiftDay=(key,days)=>new Date(Date.parse(key+"T12:00:00Z")+days*86400000).toISOString().slice(0,10);
  function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function totalsOf(meal){const total={kcal:0,protein:0,carbs:0,fat:0};for(const item of meal.items){const part=C.foodTotals(item.food,item.grams);for(const key of Object.keys(total))total[key]+=part[key];}return total;}
  class App {
    constructor({mount,mode="mirror",onState=()=>{}}){
      this.root=mount;this.mode=mode;this.onState=onState;this.state=null;this.foods=[];this.busy=false;this.modal=null;this.loading=false;
      this.root.className="diet-app diet-"+mode;this.dashboard=el("div","diet-dashboard");this.status=el("p","diet-status");this.status.setAttribute("role","status");this.root.append(this.dashboard,this.status);
      this.onKey=event=>{if(event.key==="Escape")this.closeModal();};
      document.addEventListener("keydown",this.onKey);
      this.poll=setInterval(()=>this.load(),3000);this.minute=Math.floor(Date.now()/60000);this.tick=setInterval(()=>{const minute=Math.floor(Date.now()/60000);if(minute!==this.minute){this.minute=minute;this.render();if(this.modal?.kind==="history")this.renderHistory();}},1000);this.load(true);
    }
    button(text,action,className="",label){const node=el("button",className,text);node.type="button";if(label)node.setAttribute("aria-label",label);node.onclick=()=>{if(!this.busy)action();};return node;}
    getDay(key=C.dayKey()){return this.state.days[key]||C.emptyDay(key,C.goalsForDay(this.state,key));}
    accept(state){if(this.state&&state.revision<this.state.revision)return;this.state=state;this.foods=[...this.foods.filter(food=>!food.id.startsWith("custom-")),...state.customFoods];this.onState(state);this.render();if(this.modal?.kind==="history")this.renderHistory();if(this.modal?.kind==="day")this.renderDay(this.modal.key);if(this.modal?.kind==="foods")this.renderFoods();}
    async load(first=false){
      if(this.loading||this.busy)return;this.loading=true;
      try{if(!first&&this.state&&this.foods.length){const response=await fetch(API+"/revision",{cache:"no-store"}),value=await response.json();if(!response.ok)throw new Error(value.error||"Could not connect.");if(value.revision===this.state.revision)return;}const requests=[fetch(API+"/state",{cache:"no-store"})];if(first||!this.foods.length)requests.push(fetch(API+"/foods",{cache:"no-store"}));const responses=await Promise.all(requests);const data=await Promise.all(responses.map(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error||"Could not load your diary.");return value;}));if(this.busy)return;if(data[1])this.foods=data[1];if(!this.state||data[0].revision>this.state.revision)this.accept(data[0]);}
      catch(error){this.message(error.message,true);}finally{this.loading=false;}
    }
    message(text,error=false){this.status.textContent=text;this.status.classList.toggle("diet-error",error);if(this.modal){this.modal.status.textContent=text;this.modal.status.classList.toggle("diet-error",error);}}
    async change(method,url,body){
      if(this.busy)return false;if(this.modal&&[...this.modal.panel.querySelectorAll('input[type="number"]')].some(input=>!input.value.trim()||!input.validity.valid)){this.message("Enter valid quantities.",true);return false;}this.busy=true;this.root.classList.add("diet-saving");this.message("Saving…");
      try{const response=await fetch(API+url,{method,headers:{"Content-Type":"application/json","X-Diet-Client":"MMM-DietCalories"},...(body!==undefined?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not save.");this.accept(data);if(url==="/foods")this.foods=[...this.foods.filter(food=>!food.id.startsWith("custom-")),...data.customFoods];this.message("Saved to the mirror");return true;}
      catch(error){this.message(error.message,true);return false;}finally{this.busy=false;this.root.classList.remove("diet-saving");}
    }
    metric(key,day,large=false){
      const stats=C.summary(day),block=el("div","diet-metric"+(large?" diet-energy":""));block.append(el("h3","",LABELS[key]));
      const unit=key==="kcal"?"kcal":key==="water"?"ml":"g";
      const row=el("div","diet-metric-number");row.append(el("strong","",fmt(stats.totals[key],key==="kcal"||key==="water"?0:1)),el("span","",` / ${fmt(day.goals[key])} ${unit}`));block.append(row);
      const track=el("div","diet-progress"),bar=el("div","diet-progress-fill");bar.style.width=Math.min(100,stats.percent[key])+"%";track.append(bar);track.setAttribute("role","progressbar");track.setAttribute("aria-label",LABELS[key]);track.setAttribute("aria-valuemin","0");track.setAttribute("aria-valuemax","100");track.setAttribute("aria-valuenow",String(Math.min(100,stats.percent[key])));track.setAttribute("aria-valuetext",stats.percent[key]+"% of the goal logged");block.append(track);
      const note=stats.percent[key]>=100?`${stats.percent[key]}% logged · goal reached`:`${stats.percent[key]}% · remaining ${fmt(stats.remaining[key],1)} ${unit}`;block.append(el("small","",note));return block;
    }
    render(){
      if(!this.state){this.dashboard.replaceChildren(el("p","","Loading your diary…"));return;}
      const day=this.getDay(),stats=C.summary(day),header=el("header","diet-header"),title=el("div","diet-title");
      header.append(this.button("◷ History",()=>this.openHistory(),"diet-history-open","Open history"));title.append(el("p","diet-eyebrow","NUTRITION · TODAY"),el("h2","",dateLabel(day.key)));header.append(title,this.button("Goals",()=>this.openGoals(),"diet-settings","Edit goals"));
      const macros=el("div","diet-macros");for(const key of ["protein","carbs","fat"])macros.append(this.metric(key,day));
      const water=el("section","diet-water");water.append(this.metric("water",day));const waterActions=el("div","diet-water-actions");waterActions.append(this.button("+ 250 ml",()=>this.change("POST","/water",{day:day.key,ml:250})),this.button("+ 500 ml",()=>this.change("POST","/water",{day:day.key,ml:500})),this.button("View entries",()=>this.openDay(day.key)));water.append(waterActions);
      const meals=el("section","diet-today-meals"),mealHeader=el("div","diet-section-header");mealHeader.append(el("h3","","Your meals"),this.button("Add meal",()=>this.openMeal(day.key),"diet-primary"));meals.append(mealHeader);
      if(!day.meals.length)meals.append(el("p","diet-empty","Choose a meal and log your food. Your totals will appear here."));
      else{const list=el("div","diet-meal-grid");for(const meal of day.meals.slice(-6)){const total=totalsOf(meal),button=this.button("",()=>this.openMeal(day.key,meal),"diet-meal-card","Edit "+meal.kind+": "+meal.items.map(i=>i.food.name).join(", "));button.append(el("strong","",meal.kind),el("span","",meal.items.map(i=>`${fmt(i.quantity,1)} ${i.unit} · ${i.food.name}`).join("; ")),el("small","",`${fmt(total.kcal)} kcal · P ${fmt(total.protein,1)} g · C ${fmt(total.carbs,1)} g · F ${fmt(total.fat,1)} g`));list.append(button);}meals.append(list);if(day.meals.length>6)meals.append(this.button("View all meals",()=>this.openDay(day.key)));}
      const reminder=C.reminder(day,new Date(),this.state.profile.name),footer=el("footer","diet-footer");footer.append(el("span","","New day at 01:00 · Recife time"),this.button("Add food from a label",()=>this.openCustomFood()));
      this.dashboard.replaceChildren(header,this.metric("kcal",day,true),macros,water,meals,...(reminder?[el("p","diet-reminder",reminder)]:[]),footer);
    }
    dialog(title,kind){
      this.closeModal();const overlay=el("div","diet-overlay diet-"+this.mode);overlay.dataset.dietModal="true";const panel=el("section","diet-dialog");panel.setAttribute("role","dialog");panel.setAttribute("aria-modal","true");panel.setAttribute("aria-label",title);
      panel.dataset.dietKind=kind;const head=el("header","diet-dialog-heading"),heading=el("h2","",title);head.append(heading,this.button("×",()=>this.closeModal(),"diet-close","Close dialog"));const body=el("div","diet-dialog-body"),actions=el("footer","diet-dialog-actions"),status=el("p","diet-status");status.setAttribute("role","status");panel.append(head,body,actions,status);overlay.append(panel);document.body.append(overlay);this.root.inert=true;document.body.classList.add("diet-modal-on");this.modal={overlay,panel,heading,body,actions,status,kind};return this.modal;
    }
    closeKeyboard(){this.keyboard?.remove();this.keyboard=null;if(this.modal)this.modal.panel.inert=false;document.body.classList.remove("diet-keyboard-on");}
    closeModal(){this.closeKeyboard();if(this.modal){this.modal.overlay.dispatchEvent(new Event("diet-dispose"));this.modal.overlay.remove();this.modal=null;}this.root.inert=false;document.body.classList.remove("diet-modal-on");}
    scroller(contents,label){
      const shell=el("div","diet-scroll-shell"),view=el("div","diet-scroll-view");view.setAttribute("aria-label",label);view.append(contents);
      const controls=el("div","diet-scroll-controls"),track=el("div","diet-scroll-track"),thumb=this.button("",()=>{},"diet-scroll-thumb","Drag to scroll "+label);track.append(thumb);
      controls.append(this.button("↑",()=>{view.scrollTop-=view.clientHeight*.65;},"","Scroll list up"),track,this.button("↓",()=>{view.scrollTop+=view.clientHeight*.65;},"","Scroll list down"));shell.append(view,controls);
      const fit=()=>{const range=view.scrollHeight-view.clientHeight,minimum=parseFloat(getComputedStyle(thumb).minHeight)||40;const height=Math.min(track.clientHeight,Math.max(minimum,track.clientHeight*view.clientHeight/Math.max(view.clientHeight,view.scrollHeight)));thumb.style.height=height+"px";thumb.style.top=(range>0?(track.clientHeight-height)*view.scrollTop/range:0)+"px";};view.addEventListener("scroll",fit);const observer=new ResizeObserver(fit);observer.observe(view);observer.observe(contents);this.modal?.overlay.addEventListener("diet-dispose",()=>observer.disconnect(),{once:true});requestAnimationFrame(fit);
      track.addEventListener("pointerdown",event=>{if(event.pointerType!=="mouse"&&event.pointerType!=="touch")return;track.setPointerCapture(event.pointerId);const move=e=>this.scrollToY({view,track,thumb},e.clientY);move(event);track.onpointermove=move;track.onpointerup=()=>{track.onpointermove=null;track.onpointerup=null;};});
      return shell;
    }
    scrollToY(drag,y){const rect=drag.track.getBoundingClientRect(),height=drag.thumb.getBoundingClientRect().height;const ratio=Math.max(0,Math.min(1,(y-rect.top-height/2)/Math.max(1,rect.height-height)));drag.view.scrollTop=ratio*Math.max(0,drag.view.scrollHeight-drag.view.clientHeight);}
    openHistory(){this.historyOffset=0;this.dialog("History","history");this.renderHistory();}
    renderHistory(){
      const modal=this.modal;if(!modal||modal.kind!=="history")return;const keys=C.historyKeys(this.state),start=Math.max(0,Math.min(this.historyOffset,Math.floor((keys.length-1)/12)*12));this.historyOffset=start;
      const grid=el("div","diet-history-grid");for(const key of keys.slice(start,start+12)){
        const day=this.getDay(key),stats=C.summary(day),card=this.button("",()=>this.openDay(key),"diet-history-card","Open day "+dateLabel(key));card.append(el("strong","",dateLabel(key)),el("span","diet-history-percent",stats.recorded?stats.percent.kcal+"% calories":"No entries"));
        if(stats.recorded){card.append(el("small","",`P ${stats.percent.protein}% · C ${stats.percent.carbs}% · F ${stats.percent.fat}%`));const bar=el("div","diet-progress"),fill=el("div","diet-progress-fill");fill.style.width=Math.min(100,stats.percent.kcal)+"%";bar.append(fill);card.append(bar);}grid.append(card);
      }
      const nav=el("nav","diet-history-nav");nav.append(this.button("More recent days",()=>{if(start>0){this.historyOffset-=12;this.renderHistory();}}),el("span","",`${start+1}–${Math.min(start+12,keys.length)} of ${keys.length}`),this.button("Earlier days",()=>{if(start+12<keys.length){this.historyOffset+=12;this.renderHistory();}}));
      modal.overlay.dispatchEvent(new Event("diet-dispose"));modal.body.replaceChildren(el("p","diet-note","Calories are highlighted. P: protein · C: carbohydrates · F: fat. Each day runs from 01:00 to 00:59 the following day."),this.scroller(grid,"history days"));modal.actions.replaceChildren(nav);
    }
    openDay(key){this.dialog(dateLabel(key),"day");this.modal.key=key;this.renderDay(key);}
    renderDay(key){
      const modal=this.modal;if(!modal||modal.kind!=="day")return;const day=this.getDay(key),stats=C.summary(day),content=el("div","diet-day-content"),macros=el("div","diet-macros");
      modal.overlay.dispatchEvent(new Event("diet-dispose"));
      content.append(el("p","diet-note",`Day ${dateLabel(key)} · 01:00 to ${dateLabel(shiftDay(key,1))} at 00:59`),this.metric("kcal",day,true));for(const k of ["protein","carbs","fat"])macros.append(this.metric(k,day));content.append(macros,this.metric("water",day));
      if(!stats.recorded)content.append(el("p","diet-empty","No entries for this day."));
      for(const meal of day.meals){const box=el("article","diet-detail-meal"),top=el("div","diet-section-header"),t=totalsOf(meal);top.append(el("h3","",meal.kind),this.button("Edit",()=>this.openMeal(key,meal),"","Edit meal on "+dateLabel(key)));box.append(top);for(const item of meal.items){const p=C.foodTotals(item.food,item.grams);box.append(el("p","",`${item.food.name} · ${fmt(item.quantity,1)} ${item.unit} (${fmt(item.grams,1)} g) · ${fmt(p.kcal)} kcal`));}box.append(el("small","",`Total: ${fmt(t.kcal)} kcal · protein ${fmt(t.protein,1)} g · carbohydrates ${fmt(t.carbs,1)} g · fat ${fmt(t.fat,1)} g`));content.append(box);}
      if(day.water.length){const records=el("div","diet-water-records");records.append(el("h3","","Water entries"));for(const entry of day.water){const row=el("div","diet-section-header");row.append(el("span","",`${fmt(entry.ml)} ml`),this.button("Remove",()=>this.askRemoveWater(key,entry.id),"","Remove entry of "+entry.ml+" ml"));records.append(row);}content.append(records);}
      content.append(el("p","diet-note","Percentages use the goals for this day. Totals reflect the food you logged."));const scroll=this.scroller(content,"day details"),footer=el("div","diet-modal-actions");footer.append(this.button("Back to history",()=>this.openHistory()),this.button("Add meal to this day",()=>this.openMeal(key),"diet-primary"));modal.body.replaceChildren(scroll);modal.actions.replaceChildren(footer);
    }
    openMeal(key=C.dayKey(),meal=null){
      const draft={day:key,kind:meal?.kind||C.MEALS[0],items:meal?meal.items.map(i=>({food:i.food,grams:i.grams,quantity:i.quantity,unit:i.unit,factor:i.grams/i.quantity})):[],id:meal?.id,version:meal?.version};this.dialog(meal?"Edit meal":"Add meal","meal");this.modal.draft=draft;this.renderMeal();
    }
    renderMeal(){
      const modal=this.modal,draft=modal?.draft;if(!draft||this.editingNumber)return;modal.overlay.dispatchEvent(new Event("diet-dispose"));const date=el("div","diet-date-select");date.append(this.button("‹",()=>{draft.day=shiftDay(draft.day,-1);this.renderMeal();},"","Previous meal day"),el("strong","",dateLabel(draft.day)),this.button("›",()=>{if(draft.day<C.dayKey()){draft.day=shiftDay(draft.day,1);this.renderMeal();}},"","Next meal day"));
      if(draft.id)date.replaceChildren(el("strong","",dateLabel(draft.day)));
      const kinds=el("div","diet-meal-kinds");for(const kind of C.MEALS){const button=this.button(kind,()=>{draft.kind=kind;this.renderMeal();},draft.kind===kind?"diet-selected":"");button.setAttribute("aria-pressed",String(draft.kind===kind));kinds.append(button);}
      const rows=el("div","diet-draft-items");if(!draft.items.length)rows.append(el("p","diet-empty","Add the food you ate."));
      draft.items.forEach((item,index)=>{const row=el("article","diet-draft-row"),head=el("div","diet-section-header");head.append(el("strong","",item.food.name),this.button("×",()=>{draft.items.splice(index,1);this.renderMeal();},"","Remove "+item.food.name));row.append(head);
        const quantity=this.stepper("Quantity of "+item.food.name,item.quantity,item.unit==="g"?25:1,value=>{item.quantity=value;item.grams=item.quantity*(item.unit==="g"?1:item.factor||item.grams/Math.max(.01,item.quantity));this.renderMeal();},item.unit==="g"?0.1:.01,5000);
        const options=el("div","diet-unit-options");options.append(this.button("Grams",()=>{item.unit="g";item.quantity=item.grams;item.factor=1;this.renderMeal();},item.unit==="g"?"diet-selected":""));
        for(const portion of item.food.portions){options.append(this.button(portion.name,()=>{item.unit=portion.name;item.quantity=1;item.factor=portion.grams;item.grams=portion.grams;this.renderMeal();},item.unit===portion.name?"diet-selected":""));}
        options.append(this.button("Custom unit / serving",()=>{const factor=item.unit==="g"?item.grams:item.grams/Math.max(.01,item.quantity);item.unit="unit (entered weight)";item.factor=factor;item.quantity=1;item.grams=factor;this.renderMeal();}));row.append(options,quantity);
        if(item.unit!=="g"){const factor=item.factor||item.grams/item.quantity;row.append(this.stepper("Grams per unit of "+item.food.name,factor,5,value=>{item.factor=value;item.grams=item.quantity*value;this.renderMeal();},.1,5000));}
        row.append(el("small","",`${fmt(item.grams,1)} g edible portion · ${fmt(C.foodTotals(item.food,item.grams).kcal)} kcal · ${item.food.source}`));rows.append(row);
      });
      const total=totalsOf({items:draft.items}),summary=el("p","diet-draft-total",`${fmt(total.kcal)} kcal · P ${fmt(total.protein,1)} g · C ${fmt(total.carbs,1)} g · F ${fmt(total.fat,1)} g`),actions=el("div","diet-modal-actions");actions.append(this.button("Add food",()=>this.openFoods(draft)),this.button("Save meal",async()=>{const body={day:draft.day,kind:draft.kind,items:draft.items.map(i=>({foodId:i.food.id,grams:i.grams,unit:i.unit,quantity:i.quantity})),...(draft.id?{version:draft.version}:{})};if(await this.change(draft.id?"PATCH":"POST",draft.id?`/days/${draft.day}/meals/${draft.id}`:"/meals",body))this.closeModal();},"diet-primary"));
      if(draft.id)actions.append(this.button("Delete meal",()=>this.askRemoveMeal(draft)));
      modal.body.replaceChildren(date,kinds,this.scroller(rows,"meal items"),summary,el("p","diet-note","Unit weights are approximate. Adjust grams per unit or use a measured weight. Toast varies by brand and size."));modal.actions.replaceChildren(actions);
    }
    stepper(label,value,step,change,min,max){
      const box=el("label","diet-stepper"),input=el("input"),displayLabel=label.startsWith("Quantity of ")?"Quantity":label.startsWith("Grams per unit of ")?"Grams per unit":label;let current=value;const set=(v,typing=false)=>{if(v>=min&&v<=max){current=v;if(!typing)input.value=String(C.round(v));this.editingNumber=typing;try{change(v);}finally{this.editingNumber=false;}}};input.type="number";input.required=true;input.min=String(min);input.max=String(max);input.step="any";input.value=String(C.round(value));input.setAttribute("aria-label",label);input.oninput=()=>{if(input.value.trim())set(Number(input.value),true);};input.onchange=()=>set(Number(input.value));this.enableKeyboard(input,"numeric",v=>set(Number(v)));box.append(el("span","",displayLabel),this.button("−",()=>set(Math.max(min,C.round(current-step))),"","Decrease "+label),input,this.button("+",()=>set(Math.min(max,C.round(current+step))),"","Increase "+label));return box;
    }
    openFoods(draft){
      this.dialog("Choose food","foods");this.modal.draft=draft;this.foodFilter={query:"",group:"All",favorites:false};const modal=this.modal,toolbar=el("div","diet-food-toolbar"),input=el("input");input.type="search";input.placeholder="Search food…";input.setAttribute("aria-label","Search food");input.oninput=()=>{this.foodFilter.query=input.value;this.renderFoods();};this.enableKeyboard(input,"text",value=>{input.value=value;this.foodFilter.query=value;this.renderFoods();});toolbar.append(input,this.button("Categories",()=>this.openCategories()),this.button("Favorites",()=>{this.foodFilter.favorites=!this.foodFilter.favorites;this.renderFoods();}));
      modal.foodList=el("div","diet-food-list");modal.count=el("p","diet-food-count");modal.selection=el("p","diet-selection-count");modal.body.append(toolbar,modal.count,this.scroller(modal.foodList,"food catalogue"),el("small","diet-note",`Local catalogue: ${this.foods.length} foods · TACO / NEPA–Unicamp, 2011. Values per 100 g.`));modal.actions.append(modal.selection,this.button("Done selecting",()=>{this.dialog(draft.id?"Edit meal":"Add meal","meal");this.modal.draft=draft;this.renderMeal();},"diet-primary"));this.renderFoods();
    }
    renderFoods(){
      const modal=this.modal;if(modal?.kind!=="foods")return;const normalize=value=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();const aliases={aubergine:"eggplant",courgette:"zucchini",manioc:"cassava",maize:"corn"};const filter=this.foodFilter,tokens=normalize(filter.query).split(" ").filter(word=>word&&!["a","an","the","and","of"].includes(word)).map(word=>aliases[word]||(word.endsWith("s")?word.slice(0,-1):word)),list=this.foods.filter(food=>(filter.group==="All"||food.group===filter.group)&&(!filter.favorites||this.state.favorites.includes(food.id))&&tokens.every(token=>normalize(food.name).includes(token)));
      modal.count.textContent=`${list.length} ${list.length===1?"food":"foods"} · ${filter.group}${filter.favorites?" · favorites":""}`;modal.selection.textContent=`${modal.draft.items.length} food ${modal.draft.items.length===1?"item":"items"} in this meal`;
      modal.foodList.replaceChildren();for(const food of list){const row=el("div","diet-food-row"),button=this.button("",()=>{if(modal.draft.items.length>=40){this.message("This meal can contain up to 40 food items.",true);return;}const p=food.portions[0];modal.draft.items.push({food,quantity:p?1:100,unit:p?p.name:"g",grams:p?p.grams:100,factor:p?p.grams:1});modal.selection.textContent=`${modal.draft.items.length} food ${modal.draft.items.length===1?"item":"items"} in this meal`;this.message("Added: "+food.name);},"diet-food-choice","Add "+food.name);button.append(el("strong","",food.name),el("small","",`${fmt(food.per100.kcal)} kcal · P ${fmt(food.per100.protein,1)} g · C ${fmt(food.per100.carbs,1)} g · F ${fmt(food.per100.fat,1)} g / 100 g`));const favorite=this.state.favorites.includes(food.id);row.append(button,this.button(favorite?"★":"☆",async()=>{if(await this.change("PUT","/favorites",{foodId:food.id,selected:!favorite}))this.renderFoods();},"diet-favorite",(favorite?"Remove favorite: ":"Favorite: ")+food.name));modal.foodList.append(row);}if(!list.length)modal.foodList.append(el("p","diet-empty","No food found. Try another category or search."));
    }
    openCategories(){
      const modal=this.modal,backdrop=el("div","diet-categories"),grid=el("div","diet-category-grid");grid.setAttribute("role","dialog");grid.setAttribute("aria-label","Food categories");for(const group of ["All",...new Set(this.foods.map(f=>f.group))])grid.append(this.button(group,()=>{this.foodFilter.group=group;backdrop.remove();this.renderFoods();}));grid.append(this.button("Cancel",()=>backdrop.remove()));backdrop.append(grid);modal.panel.append(backdrop);
    }
    enableKeyboard(input,mode,commit){if(this.mode!=="mirror")return;input.onclick=()=>this.openKeyboard(input,mode,commit);}
    openKeyboard(input,mode,commit){
      this.closeKeyboard();const keyboard=el("section","diet-keyboard diet-"+this.mode);keyboard.dataset.dietKeyboard="true";keyboard.setAttribute("role","dialog");keyboard.setAttribute("aria-label","On-screen keyboard");const value=el("input");value.value=input.value;value.readOnly=true;value.setAttribute("aria-label","Keyboard text");const grid=el("div","diet-key-grid"),actions=el("div","diet-key-actions"),letters=mode==="numeric"?"1234567890.":"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";for(const key of letters)grid.append(this.button(key,()=>{value.value+=key;}));actions.append(this.button("Space",()=>{value.value+=" ";}),this.button("⌫",()=>{value.value=value.value.slice(0,-1);},"","Delete last character"),this.button("Clear",()=>{value.value="";}),this.button("Done",()=>{const text=value.value;this.closeKeyboard();commit(text);},"diet-primary"),this.button("Cancel",()=>this.closeKeyboard()));keyboard.append(value,grid,actions);document.body.append(keyboard);this.keyboard=keyboard;if(this.modal)this.modal.panel.inert=true;document.body.classList.add("diet-keyboard-on");
    }
    openGoals(){
      const modal=this.dialog("Your goals","goals"),draft={...this.state.goals},fields=el("div","diet-goal-fields");for(const key of C.KEYS)fields.append(this.stepper(LABELS[key]+(key==="kcal"?" (kcal)":key==="water"?" (ml)":" (g)"),draft[key],key==="kcal"?50:key==="water"?250:5,value=>{draft[key]=value;},key==="kcal"?1200:key==="water"?100:1,key==="kcal"?6000:key==="water"?8000:1000));
      const estimate=C.estimate(this.state.profile),content=el("div");content.append(el("p","diet-note",`${this.state.profile.name} · ${this.state.profile.age} years · ${this.state.profile.weight} kg · ${this.state.profile.height} cm. Goal: ${this.state.profile.targetWeight} kg in ${this.state.profile.months} months.`),fields,el("p","diet-note",`Starting estimate: resting energy ${fmt(estimate.resting)} kcal, maintenance ${fmt(estimate.maintenance)} kcal. Assumed activity factor 1.5 and an extra 100 kcal. Adjust based on weight trends; no deadline is guaranteed. Water is an editable logging goal.`),el("p","diet-note","Changing goals affects today and future days. Goals for earlier days are preserved."));modal.body.append(this.scroller(content,"goals"));modal.actions.append(this.button("Save goals",async()=>{if(await this.change("PUT","/goals",{goals:draft}))this.closeModal();},"diet-primary"));
    }
    openCustomFood(){
      const modal=this.dialog("Food from a label","custom"),name=el("input"),draft={kcal:0,protein:0,carbs:0,fat:0};name.placeholder="Name and brand";name.maxLength=120;name.setAttribute("aria-label","Food name and brand");this.enableKeyboard(name,"text",value=>{name.value=value;});const form=el("div","diet-goal-fields");form.append(name);for(const key of Object.keys(draft))form.append(this.stepper(LABELS[key]+" per 100 g",draft[key],key==="kcal"?10:1,value=>{draft[key]=value;},0,key==="kcal"?1000:100));modal.body.append(el("p","diet-note","Enter the label values per 100 g. If the label only lists values per serving, convert them to 100 g first."),this.scroller(form,"nutrition label values"));modal.actions.append(this.button("Add food",async()=>{if(await this.change("POST","/foods",{name:name.value,per100:draft}))this.closeModal();},"diet-primary"));
    }
    askRemoveMeal(draft){const modal=this.dialog("Delete meal?","confirm");modal.body.append(el("p","",`Delete ${draft.kind} on ${dateLabel(draft.day)}? Totals will be recalculated.`),this.button("Cancel",()=>this.openDay(draft.day)),this.button("Confirm deletion",async()=>{if(await this.change("DELETE",`/days/${draft.day}/meals/${draft.id}`,{version:draft.version}))this.openDay(draft.day);}));}
    askRemoveWater(key,id){const modal=this.dialog("Remove water entry?","confirm");modal.body.append(this.button("Cancel",()=>this.openDay(key)),this.button("Confirm removal",async()=>{if(await this.change("DELETE",`/days/${key}/water/${id}`))this.openDay(key);}));}
    destroy(){clearInterval(this.poll);clearInterval(this.tick);this.closeModal();document.removeEventListener("keydown",this.onKey);}
  }
  root.DietUI={App};
})(globalThis);
